# Generated by Django 4.0.10 on 2024-05-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_youth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youth',
        ),
    ]
